baseurl: "/Kadaster"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Imvertor documentatie
    subnav:
      - title: Algemeen
        url: https://melsk-r.github.io/Imvertor-organisaties/
        path: /
  - title: Kadaster specifieke documentatie
    subnav:
      - title: Inleiding
        path: /index
      - title: Installatie
        path: /installatie
      - title: Begrippen
        path: /begrippen
      - title: Handreikingen
        path: /handreikingen
      - title: Wetenswaardigheden en specials
        path: /wetenswaardigheden-en-specials
      - title: Veel voorkomende foutens
        path: /veel-voorkomende-fouten
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  
remote_theme: VNG-Realisatie/jekyll-theme-imvertor

github: melsk-r/Kadaster
theme: jekyll-theme-time-machine

project_name: /Imvertor
